{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "3e5720f9-1bd9-4c74-b2a0-34afdd766090",
   "metadata": {},
   "outputs": [],
   "source": [
    "#install libraries if necessary (i.e. uncomment and run this code)\n",
    "# import Pkg\n",
    "# Pkg.add(\"JuMP\")\n",
    "# Pkg.add(\"Ipopt\")\n",
    "# Pkg.add(\"XLSX\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "136f43f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "#We import our data for import shares\n",
    "import XLSX\n",
    "xf = XLSX.readxlsx(\"../data/data/processed/Import_to_GDP_2019.xlsx\")\n",
    "sh = xf[\"2019final\"]\n",
    "target_import_shares_H = sh[\"F2:F5\"]\n",
    "target_import_shares_F = 1\n",
    ";"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "c8f2644c-16a3-4470-9106-78c14702134d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# do importing work in this tab\n",
    "using JuMP\n",
    "using Ipopt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "90c87b01-1339-4446-8ce7-230740f722ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "debug = false\n",
    "\n",
    "# set up global params\n",
    "global nc = 5 # number of counties\n",
    "global ni = 4 # number of industries\n",
    "global η = 0 # the spill-over effect\n",
    "global τ = 1 # trade frictions\n",
    "global ρ = 2.5 # the elasiticity of substitution within industry\n",
    "global σ = 1.7 # the elasiticity of substitution across industries\n",
    "global L_H = 1 # total mass of labor at home country\n",
    "global L_F = 1 # total mass of labor at foreign country\n",
    "global w_H_init = 1\n",
    "global Markup_H = 1/(ρ-1) # markup of firm\n",
    "global E_H = (Markup_H + 1) * w_H_init # expenditure\n",
    "\n",
    "# global z_H = Matrix((ones(Float64, ni, nc))) # home productivity\n",
    "# global z_F = Matrix(ones(Float64, ni, 1)) # foreign productivity\n",
    "\n",
    "company_sizes_H = [1/ni for i=1:ni, c=1:nc] \n",
    "#takes on the role of μ_lb and μ_ub below\n",
    "#represents the size of a company relative to the population in the county, range (0,1)\n",
    "#@show company_sizes_H #<-- if one would like to debug\n",
    "\n",
    "# The variables below have solid mathematical reason for being here, but don't seem practical\n",
    "# to me from a programming perspective. It seems they merely define the relative size of a\n",
    "# company; this can be represented with 1 number instead of 2. \n",
    "# μ_lb = Matrix{Real}([0 0.5; 0 0.5])\n",
    "# # the entries before the semi-colon is industry 1 for all counties\n",
    "# μ_ub = Matrix{Real}([0.5 1; 0.5 1])\n",
    "\n",
    "; #eliminates output from this cell"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "cf3c7b2f-90f6-421d-b475-ac9d80475542",
   "metadata": {},
   "outputs": [],
   "source": [
    "#MAKE JuMP MODEL\n",
    "\n",
    "debug = false #changes debug for this cell\n",
    "\n",
    "#Make model and its vars\n",
    "model = Model(Ipopt.Optimizer)\n",
    "set_silent(model)\n",
    "industries = 1:ni\n",
    "counties = 1:nc\n",
    "\n",
    "#labor for each industry-county (home production for home consumption), denoted lhh\n",
    "@variable(model, lhh[industries, counties] >= 0)\n",
    "\n",
    "#labor for each industry-county (home production for foreign consumption), denoted lhf\n",
    "@variable(model, lhf[industries, counties] >= 0)\n",
    "\n",
    "#labor for each industry (foreign production for home consumption), denoted lfh\n",
    "@variable(model, lfh[industries] >= 0)\n",
    "\n",
    "#labor for each industry (foreign production for foreign consumption), denoted lff\n",
    "@variable(model, lff[industries] >= 0)\n",
    "\n",
    "#productivity for each industry-county (home production for both markets), denoted z_H\n",
    "@variable(model, z_H[industries, counties] >= 0)\n",
    "\n",
    "#productivity for each industry (foreign production for both markets), denoted z_F\n",
    "@variable(model, z_F[industries] >= 0)\n",
    "\n",
    "#wage at Home, normalised to 1\n",
    "@NLparameter(model, w_H == 1)\n",
    "#wage at Foreign, some positive number relative to w_H\n",
    "@variable(model, w_F >= 0)\n",
    "\n",
    "#show what these look like, purely for debugging\n",
    "if(debug)\n",
    "    @show lhh\n",
    "    @show lhf\n",
    "    @show lfh\n",
    "    @show lff\n",
    "end"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "867e6071",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Here we make expressions that mirror functions. It seems that functions might\n",
    "#not work as desired, so we might be forced to use expressions. Yuck.\n",
    "\n",
    "L_ic_H = @NLexpression(model, [i=industries, c=counties], company_sizes_H[i,c] * (lhh[i,c] + lhf[i,c]))\n",
    "\n",
    "E_F = @NLexpression(model, E_H * w_F)\n",
    "\n",
    "pv_ic_H = @NLexpression(model, [i=industries, c=counties], E_H * w_H  / (z_H[i,c] * L_ic_H[i,c] ^ η))\n",
    "pv_ic_Hx = @NLexpression(model, [i=industries, c=counties], E_H * w_H / (z_H[i,c] * L_ic_H[i,c] ^ η))\n",
    "pv_if_F = @NLexpression(model, [i=industries], E_F / z_F[i])\n",
    "pv_if_Fx = @NLexpression(model, [i=industries], E_F / z_F[i])\n",
    "\n",
    "H_sum = @NLexpression(model, [i=industries], sum((company_sizes_H[i,c] * pv_ic_H[i,c]^(1-ρ)) for c=counties))\n",
    "F_sum = @NLexpression(model, [i=industries], τ * pv_if_F[i]^(1-ρ))\n",
    "p_i_H = @NLexpression(model, [i=industries], H_sum[i] + F_sum[i])\n",
    "\n",
    "Hx_sum = @NLexpression(model, [i=industries], sum((company_sizes_H[i,c] * (τ * pv_ic_Hx[i,c])^(1-ρ)) for c=counties))\n",
    "Fx_sum = @NLexpression(model, [i=industries], (pv_if_Fx[i])^(1-ρ))\n",
    "p_i_F = @NLexpression(model, [i=industries], Hx_sum[i] + Fx_sum[i])\n",
    "\n",
    "p_H_sum = @NLexpression(model, sum((p_i_H[i])^(1-σ) for i=industries))\n",
    "p_H = @NLexpression(model, p_H_sum^(1/(1-σ)))\n",
    "\n",
    "p_F_sum = @NLexpression(model, sum((p_i_F[i])^(1-σ) for i=industries))\n",
    "p_F = @NLexpression(model, p_F_sum^(1/(1-σ)))\n",
    "\n",
    "yv_ic_H = @NLexpression(model, [i=industries, c=counties], pv_ic_H[i,c]^(-ρ) * p_i_H[i]^(ρ-σ) * (p_H^(σ-1)) * E_H)\n",
    "yv_ic_Hx = @NLexpression(model, [i=industries, c=counties], pv_ic_Hx[i,c]^(-ρ) * p_i_F[i]^(ρ-σ) * (p_F^(σ-1)) * E_F)\n",
    "yv_if_F = @NLexpression(model, [i=industries], pv_if_F[i]^(-ρ) * p_i_H[i]^(ρ-σ) * p_H^(σ-1) * E_H)\n",
    "yv_if_Fx = @NLexpression(model, [i=industries], pv_if_Fx[i]^(-ρ) * p_i_F[i]^(ρ-σ) * p_F^(σ-1) * E_F)\n",
    "\n",
    "exports = @NLexpression(model, sum((company_sizes_H[i,c]) * (τ * pv_ic_Hx[i,c]) * (yv_ic_Hx[i,c]) for i=industries, c=counties))\n",
    "imports = @NLexpression(model, sum((τ * pv_if_F[i]) * (yv_if_F[i]) for i=industries))\n",
    "\n",
    "pred_import_share_H = @NLexpression(model, [i=industries], (yv_if_F[i] * pv_if_F[i]) / sum((company_sizes_H[i,c])\n",
    "* (yv_ic_H[i,c] * pv_ic_H[i,c]+ yv_ic_Hx[i,c] * pv_ic_Hx[i,c]) for c=counties))\n",
    "# function import_ratio(i,l)\n",
    "#     import_sec = yv_if_F(i,l) * pv_if_F(i,l)\n",
    "#     gdp_H_sec = 0\n",
    "#     for j in counties\n",
    "#         gdp_H_sec +=  (μ_ub[i,j] - μ_lb[i,j]) * (yv_ic_H(i,j,l) * pv_ic_H(i,j,l)+ yv_ic_Hx(i,j,l) * pv_ic_Hx(i,j,l))\n",
    "#     end\n",
    "#     return import_sec/gdp_H_sec\n",
    "# end\n",
    "\n",
    "\n",
    "#These last lines mirror our original model_difference() function\n",
    "\n",
    "pred_lhh_ic = @NLexpression(model, [i=industries, c=counties], yv_ic_H[i,c] / (z_H[i,c] * L_ic_H[i,c] ^ η))\n",
    "diff_lhh_ic = @NLexpression(model, [i=industries, c=counties], pred_lhh_ic[i,c] - lhh[i,c])\n",
    "\n",
    "pred_lhf_ic = @NLexpression(model, [i=industries, c=counties], yv_ic_Hx[i,c] / (z_H[i,c] * L_ic_H[i,c] ^ η))\n",
    "diff_lhf_ic = @NLexpression(model, [i=industries, c=counties], pred_lhf_ic[i,c] - lhf[i,c])\n",
    "\n",
    "pred_lfh_i = @NLexpression(model, [i=industries], τ * yv_if_F[i] / z_F[i])\n",
    "diff_lfh_i = @NLexpression(model, [i=industries], pred_lfh_i[i] - lfh[i])\n",
    "\n",
    "pred_lff_i = @NLexpression(model, [i=industries], τ * yv_if_Fx[i] / z_F[i])\n",
    "diff_lff_i = @NLexpression(model, [i=industries], pred_lff_i[i] - lff[i])\n",
    "\n",
    "diff_lhh = @NLexpression(model, sum(diff_lhh_ic[i,c]^2 for i=industries, c=counties))\n",
    "diff_lhf = @NLexpression(model, sum(diff_lhf_ic[i,c]^2 for i=industries, c=counties))\n",
    "diff_lfh = @NLexpression(model, sum(diff_lfh_i[i]^2 for i=industries))\n",
    "diff_lff = @NLexpression(model, sum(diff_lff_i[i]^2 for i=industries))\n",
    "\n",
    "model_difference = @NLexpression(model, diff_lhh + diff_lhf + diff_lfh + diff_lff)\n",
    ";"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "951b62d9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "solution_summary(model) = * Solver : Ipopt\n",
      "\n",
      "* Status\n",
      "  Termination status : LOCALLY_SOLVED\n",
      "  Primal status      : FEASIBLE_POINT\n",
      "  Dual status        : FEASIBLE_POINT\n",
      "  Message from the solver:\n",
      "  \"Solve_Succeeded\"\n",
      "\n",
      "* Candidate solution\n",
      "  Objective value      : 0.05373895889015568\n",
      "\n",
      "* Work counters\n",
      "  Solve time (sec)   : 1.72589\n",
      "\n",
      "value.(lhh) = 2-dimensional DenseAxisArray{Float64,2,...} with index sets:\n",
      "    Dimension 1, 1:4\n",
      "    Dimension 2, 1:5\n",
      "And data, a 4×5 Matrix{Float64}:\n",
      " 0.06412271146352619   0.06412271146354181  0.0641227114635593   0.06412271146355161  0.06412271146352409\n",
      " 0.041092984855812864  0.04109298485581266  0.04109298485581285  0.0410929848558128   0.041092984855812864\n",
      " 0.048523628419044416  0.04852362841904482  0.04852362841904479  0.04852362841904453  0.04852362841904487\n",
      " 0.04561073833208159   0.04561073833208151  0.04561073833208159  0.04561073833208159  0.04561073833208157\n",
      "value.(lhf) = 2-dimensional DenseAxisArray{Float64,2,...} with index sets:\n",
      "    Dimension 1, 1:4\n",
      "    Dimension 2, 1:5\n",
      "And data, a 4×5 Matrix{Float64}:\n",
      " 0.0006489372091954887  0.0006489372091991066  0.0006489372092031579  0.0006489372092013778  0.0006489372091949991\n",
      " 2.562904565681441e-7   2.5629045656814135e-7  2.5629045656814374e-7  2.5629045656814315e-7  2.562904565681439e-7\n",
      " 4.1066132073695273e-7  4.106613207369656e-7   4.106613207369652e-7   4.106613207369563e-7   4.106613207369674e-7\n",
      " 3.3276854431716206e-7  3.327685443171602e-7   3.3276854431716206e-7  3.3276854431716206e-7  3.3276854431716174e-7\n",
      "value.(lfh) = 1-dimensional DenseAxisArray{Float64,1,...} with index sets:\n",
      "    Dimension 1, 1:4\n",
      "And data, a 4-element Vector{Float64}:\n",
      " 0.2789667885951969\n",
      " 0.08723583032158602\n",
      " 0.1444893368529523\n",
      " 0.12058370834974179\n",
      "value.(lff) = 1-dimensional DenseAxisArray{Float64,1,...} with index sets:\n",
      "    Dimension 1, 1:4\n",
      "And data, a 4-element Vector{Float64}:\n",
      " 0.12033503726045656\n",
      " 0.07577804806199782\n",
      " 0.08908337915074874\n",
      " 0.08352787140731976\n",
      "value.(z_H) = 2-dimensional DenseAxisArray{Float64,2,...} with index sets:\n",
      "    Dimension 1, 1:4\n",
      "    Dimension 2, 1:5\n",
      "And data, a 4×5 Matrix{Float64}:\n",
      " 1.0160518623032977  1.0160518623034258  1.016051862303569   1.016051862303506   1.0160518623032806\n",
      " 0.9946375983381769  0.9946375983381746  0.9946375983381766  0.994637598338176   0.9946375983381766\n",
      " 0.9975463509748913  0.9975463509748952  0.9975463509748952  0.9975463509748923  0.9975463509748955\n",
      " 0.9963530452257396  0.9963530452257389  0.9963530452257396  0.9963530452257396  0.9963530452257395\n",
      "value.(z_F) = 1-dimensional DenseAxisArray{Float64,1,...} with index sets:\n",
      "    Dimension 1, 1:4\n",
      "And data, a 4-element Vector{Float64}:\n",
      " 0.1643654063605242\n",
      " 0.03469026474549718\n",
      " 0.09200165757052625\n",
      " 0.07238694878062366\n",
      "value.(w_F) = 0.2323933155160536\n"
     ]
    }
   ],
   "source": [
    "#Set constraints for our model\n",
    "\n",
    "#Constraint: labor must never be negative. This is achieved in the variable declarations.\n",
    "\n",
    "#Constraint: labors in a country must add to the country's initial allotment of labor\n",
    "@constraint(model, sum(lhh)+sum(lhf) == L_H)\n",
    "@constraint(model, sum(lfh)+sum(lff) == L_F)\n",
    "\n",
    "#Constraint: imports must equal predicted exports (or the other way around, it doesn't matter)\n",
    "@NLconstraint(model, imports == exports)\n",
    "\n",
    "#Constraint: import ratio for industry i at Home == target import ratio for i at H (from data)\n",
    "# the predicted ratio is import_ratio(i,l):\n",
    "@NLconstraint(model, [i=industries], pred_import_share_H[i] == target_import_shares_H[i])\n",
    "\n",
    "#Constraint: import ratio for industry i at Foreign == target import ratio for i at F (from data?)\n",
    "#predicted ratio is the following value for all industries:\n",
    "# imp(l)/E_H\n",
    "# the difference is thus: imp(l)/E_H - target_F\n",
    "# foreign might be normalizable to 1, would make comparisons much easier\n",
    "# target_F = 1, according to our prior work\n",
    "\n",
    "\n",
    "#Lastly, we pass our root expression to our model as a non-linear objective.\n",
    "#Our objective needs to be non-linear to allow for our operations.\n",
    "#Objective function: minimize(| x - predicted(x) |) <-- i.e. we attempt to reach a fixed-point solution\n",
    "@NLobjective(model, Min, model_difference) #<-- this is the non-test objective to use\n",
    "#@NLobjective(model, Min, model_difference)\n",
    "#@objective(model, Min, model_difference(lhh, lhf, lfh, lff))\n",
    "\n",
    "# Run the model\n",
    "optimize!(model)\n",
    "@show solution_summary(model)\n",
    "@show value.(lhh)\n",
    "@show value.(lhf)\n",
    "@show value.(lfh)\n",
    "@show value.(lff)\n",
    "@show value.(z_H)\n",
    "@show value.(z_F)\n",
    "@show value.(w_F)\n",
    "\n",
    "; #eliminate unnecessary output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "031390d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "#THIS CONTAINS MODIFIED HELPER FUNCTIONS, DIFFERENT FROM NLsolve but equvialent in function\n",
    "\n",
    "debug = true #modifies debug for this cell\n",
    "\n",
    "#Define helper functions\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function L_ic_H(i,c)\n",
    "#     i = Int(i); c = Int(c);\n",
    "#     return company_sizes_H[i,c] * (lhh[i,c] + lhf[i,c])\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function E_F()\n",
    "#     return E_H * w_F\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function pv_ic_H(i,c)\n",
    "#     return E_H * w_H  / (z_H[i,c] * L_ic_H(i,c) ^ η)\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function pv_ic_Hx(i,c)\n",
    "#     return E_H * w_H / (z_H[i,c] * L_ic_H(i,c) ^ η)\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function pv_if_F(i)\n",
    "#     return E_F() / z_F[i]\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function pv_if_Fx(i)\n",
    "#     return  E_F() / z_F[i]\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# # industry_price_home matrix\n",
    "# function p_i_H(i) # calculate industry price index at home \n",
    "#     # domestic price aggregation\n",
    "#     H_sum = sum((company_sizes_H[i,c] * pv_ic_H(i,c)^(1-ρ)) for c in 1:nc)\n",
    "#     # foreign price aggregation\n",
    "#     F_sum = τ * pv_if_F(i)^(1-ρ)\n",
    "\n",
    "#     sum = (H_sum + F_sum)^(1/(1-ρ))\n",
    "#     return sum\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function p_i_F(i) # calculate industry price index at foreign\n",
    "#     Hx_sum = sum((company_sizes_H[i,c] * (τ * pv_ic_Hx(i,c))^(1-ρ)) for c in 1:nc)\n",
    "#     Fx_sum = (pv_if_Fx(i))^(1-ρ)\n",
    "    \n",
    "#     sum = (Hx_sum + Fx_sum)^(1/(1-ρ))\n",
    "#     return sum\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function p_H() # calculate final good price index at home\n",
    "#     sum = sum((p_i_H(i))^(1-σ) for i in 1:ni)\n",
    "#     return sum^(1/(1-σ))\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function p_F() # calculate final good price index at foreign\n",
    "#     sum = sum((p_i_F(i))^(1-σ) for i in 1:ni)\n",
    "#     return sum^(1/(1-σ))\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function yv_ic_H(i,c)\n",
    "#     return pv_ic_H(i,c)^(-ρ) * p_i_H(i)^(ρ-σ) * (p_H()^(σ-1)) * E_H\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function yv_ic_Hx(i,c)\n",
    "#     return pv_ic_Hx(i,c)^(-ρ) * p_i_F(i)^(ρ-σ) * (p_F()^(σ-1)) * E_F()\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function yv_if_F(i)\n",
    "#     return pv_if_F(i)^(-ρ) * p_i_H(i)^(ρ-σ) * p_H()^(σ-1) * E_H\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# function yv_if_Fx(i)\n",
    "#     return pv_if_Fx(i)^(-ρ) * p_i_F(i)^(ρ-σ) * p_F()^(σ-1) * E_F()\n",
    "# end\n",
    "\n",
    "# #DONE REWRITING\n",
    "# # balanced Trade\n",
    "# function exports()\n",
    "#     # Hx_sum = 0\n",
    "#     # Hx_i_sum = 0\n",
    "#     # for i in 1:ni\n",
    "#     #     Hx_i_sum = 0\n",
    "#     #     for j in 1:nc\n",
    "#     #         Hx_i_sum += (μ_ub[i,j] - μ_lb[i,j]) * (τ * pv_ic_Hx(i,j,l)) * (yv_ic_Hx(i,j,l))\n",
    "#     #     end\n",
    "#     #     Hx_sum += Hx_i_sum\n",
    "#     # end\n",
    "\n",
    "#     Hx_sum = sum((company_sizes_H[i,c]) * (τ * pv_ic_Hx(i,c)) * (yv_ic_Hx(i,c)) for i in 1:ni, c in 1:nc)\n",
    "#     return Hx_sum\n",
    "# end\n",
    "\n",
    "# function imports()\n",
    "#     # F_sum = 0\n",
    "#     # for i in 1:ni\n",
    "#     #     F_sum +=  (τ * pv_if_F(i,l)) * (yv_if_F(i,l))\n",
    "#     # end\n",
    "\n",
    "#     F_sum = sum((τ * pv_if_F(i)) * (yv_if_F(i)) for i in 1:ni)\n",
    "#     return F_sum\n",
    "# end\n",
    "\n",
    "# #Returns the difference between the model's current guess and predicted values\n",
    "# function model_difference()\n",
    "#     diff = 0.0\n",
    "\n",
    "#     for i=1:ni\n",
    "#         for c=1:nc\n",
    "#             #only calculate once, save compute power\n",
    "#             productivity_labor_units = z_H[i,c] * L_ic_H(i,c) ^ η\n",
    "\n",
    "#             #calc diff for lhh_ic\n",
    "#             pred_lhh_ic = yv_ic_H(i,c) / productivity_labor_units\n",
    "#             diff_lhh_ic = pred_lhh_ic - lhh[i,c]\n",
    "\n",
    "#             #calc diff for lhf_ic\n",
    "#             pred_lhf_ic = yv_ic_Hx(i,c) / productivity_labor_units\n",
    "#             diff_lhf_ic = pred_lhf_ic - lhf[i,c]\n",
    "\n",
    "#             diff += diff_lhh_ic^2 + diff_lhf_ic^2\n",
    "#         end\n",
    "#         #calc diff for lfh_i\n",
    "#         pred_lfh_i = τ * yv_if_F(i) / z_F[i]\n",
    "#         diff_lfh_i = pred_lfh_i - lfh[i]\n",
    "\n",
    "#         #calc diff for lff_i\n",
    "#         pred_lff_i = τ * yv_if_Fx(i) / z_F[i]\n",
    "#         diff_lff_i = pred_lff_i - lff[i]\n",
    "\n",
    "#         diff += diff_lfh_i^2 + diff_lff_i^2\n",
    "#     end\n",
    "\n",
    "#     return diff\n",
    "# end\n",
    "\n",
    "# #<<FOR TESTING PURPOSES>>\n",
    "# function model_difference_test(lhh, lhf, lfh, lff)\n",
    "#     # diff_lhh = sum((lhh[i,j])^2 for i=1:ni, j=1:nc)\n",
    "#     # diff_lff = sum((lff[i])^2 for i=1:ni)\n",
    "#     return sum(E_H * w_H  / (z_H[i,c] * L_ic_H(i,c,lhh,lhf) ^ η) for i=1:ni, c=1:nc)\n",
    "#     # return 0.0\n",
    "#     # return diff_lhh+diff_lff\n",
    "# end\n",
    "\n",
    "debug = false #resets debug to false after this cell\n",
    ";"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "266aef59",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Julia 1.6.3",
   "language": "julia",
   "name": "julia-1.6"
  },
  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "julia",
   "version": "1.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
